### ISSUE TITLE
MatLab Code for Olfactometer

### ISSUE THREAD

**Issue by Gavin-Perry** [restrepd/JL-Olfactometer#1]
Do you have any working code for matlab to run an olfactometer?
I'm trying to do the same thing. I'm not sure how to get timing accurate to a msec.

**Comment by restrepd** [comment]
The software dropcspm.m in https://github.com/restrepd/dropc controls the olfactometer. The timing for delivery of the odorant to the odor cone is 104.5 ± 7 msec (mean ± SD, n = 10) (see Figure 1—figure supplement 1 in DOI: 10.7554/eLife.52583).  The delay of 104.5 msec is due to the time of air flow from the diverter valve through the tubes to the cone. The olfactometer/MATLAB code has an SD for time delivery of 7 msec, not surprising for MATLAB code and a regular computer. For more accurate delivery I would program a Teensy or FPGA. Alternately you could monitor the onset of delivery with a DAC.

**Comment by Gavin-Perry** [comment]
Thanks for your help Diego,
Your timing data is very useful.
I've been thinking about using an Arduino for the real time part.

Gavin
________________________________

**Comment by restrepd** [comment]
Yes, using an Arduino should work. We are using an Arduino UNO for closed loop stimulation at specific theta LFP phases, and it is working well.
